### ISSUE TITLE
kopano meet broken with image version 0.20.0_0

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#197] opened 2019-07-01 14:38 UTC
With the old version of 0.19.1_0, i am able to login and to start simple calls. With the current version i get the following error printed in the web-view:

```
App start failed with error
Error: unexpected Content-Type

Das ist ein schwerwiegender Fehler und die App must neu geladen werden.
```

The chromium development tools are printing the following section: 

```
app initialization failed - this is fatal Error: unexpected Content-Type
    at actions.js:114
(anonymous) @ Meet.js:65
```

Since this seems to be a problem with the meet module itslef, should i place this bug-report some-where else?

**Comment by fbartels** [comment] 2019-07-02 06:20
Hi @cguentherTUChemnitz,

yes I've noticed this error myself as well, but did not yet have the time to really dig into the cause of it.

Since this is not really about dockerising Meet, but an issue in Meet itself I would recommend to either open up a post on the [Kopano Forum](https://forum.kopano.io/) (preferred) or in its [dedicated issue tracker here on Github](https://github.com/Kopano-dev/meet).

**Comment by fbartels** [comment] 2019-07-02 08:50
Potential reason for this error (at least the is what I see in my environment) is that when the browser opens /api/config/v1/kopano/meet/config.json the content type of this file is `text/plain` instead of `application/json`.

This is probably something that needs to be fixed in the kweb.cfg in this repo after all.

**Comment by fbartels** [comment] 2019-07-04 06:39
I have not yet tried it personally, but the upstream docker image has been modified so that mime detection in the web container should work now. 

On top of this I have configured travis to start a container build, if there has been no build on the master branch within last 24 hours (we'll to be exact it does a daily build, but only if there was no build within last 24h so practically I guess the longest time between builds could be something close to 48h).

**Closed as completed by fbartels** 2019-07-04 06:39 UTC
Labels: question
