### ISSUE TITLE
password gets requested all the time (Outlook (on Windows), Gmail (on Android))

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#464] opened 2020-09-30 11:02 UTC
**Describe the bug**
every few minutes Outlook and Gmail are asking for the Password.

**To Reproduce**

1. Add the Account as an ActiveSync-Account on Outlook + Gmail
2. wait a few minutes

**Expected behavior**
it only asks once for a password

**Additional context**
what I found so far is the following log on kopano_zpush:
```kopano_zpush        | 30/09/2020 12:59:45 [   64] [FATAL] [username@domain.tld] Exception: (AuthenticationRequiredException) -                                                                             KopanoBackend->Logon(): User 'username@domain.tld' has no default store```

**Comment by fbartels** [comment] 2020-09-30 15:00
Hi @theoneandonly-vector,

I am unable to reproduce this behavior on my test system. If it would be a setup problem I would expect the device to not sync at all, but when it only appears after some time I would start to look at your infrastructure (e.g. all containers still running? ldap ok?).

**Comment by theoneandonly-vector** [comment] 2020-09-30 15:19
all dockers I need are running (disabled ldap and meet). I'm using an external LDAP for mail-docker and I authenticate kopano against it using "SASLAUTHD_MECHANISMS=rimap"

is the log entry I posted part of the error?

what I found out is, as soon as I change something on /calendar this issue happens immediately on Outlook. (not every time, but often)

**Comment by engelant** [comment] 2020-09-30 20:12
I actually also encountered this error (running against samba4).
The issue seems to be a [broken kopano core version](https://forum.kopano.io/topic/3316/can-t-contact-ldap-server/27) or to be more precise it seems that the LDAP session isn't reused.
Anyhow, as @fbartels states in ihis last post on the forum: fixing the nightly build is currently low prio.

As for the workaround I edited .env
```
# please consult https://github.com/zokradonh/kopano-docker
# for possible configuration values and their impact
CORE_VERSION=10.0.6.13
WEBAPP_VERSION=4.3.2944
ZPUSH_VERSION=latest
KONNECT_VERSION=latest
KWM_VERSION=latest
MEET_VERSION=latest
KDAV_VERSION=latest
KAPPS_VERSION=latest
SPAMD_CORE_VERSION=latest
...
```
and docker-compose.override.yml
```
  kopano_spamd:
    image: ${docker_repo:-zokradonh}/kopano_core:${SPAMD_CORE_VERSION:-latest}
```

That's the last known good core version for me.
The spamd image override is due to the updated start script. Actually not sure if it even works, but the errors about "no av engine found" went away, so...

**Comment by theoneandonly-vector** [comment] 2020-09-30 23:42
thank you very much @engelant 

I just used "CORE_VERSION=10.0.6.13" but kept "WEBAPP_VERSION=latest" seems to work so far.

Do you have an idea for me how to check if it's a bug in Kopano-Core or some other package vs a Problem with "kopano-docker"?

"running against samba4" do you use ldap directly or do you use "rimap" for kopano-authentication too?

**Comment by fbartels** [comment] 2020-10-01 06:21
Closing since its not a problem with the docker containers itself.

Generally speaking I would not recommend to use the nightly builds for production setups. Rather buy a subscription and rebuild the containers with the officially supported releases (can easily be done with the Makefile).

**Closed as completed by fbartels** 2020-10-01 06:21 UTC
Labels: question
